### ISSUE TITLE
DB edit current reservation issue

### ISSUE THREAD

**Issue by jmoore4** [rcarle3911/Hotel-Reservation-Project#133]
When updating a reservation the following error comes back:

![image](https://cloud.githubusercontent.com/assets/23193311/21288503/afd43c0e-c452-11e6-9981-22d3a4b1b78d.png)

I'm getting no availability on a reservation that already exists, even when I do not change room type or dates.

**Comment by jmoore4** [comment]
I'm wondering if it is just all of the John Smiths breaking it.

**Comment by ghost** [comment]
Smoke them all and add some diverse test data with https://www.mockaroo.com/

**Comment by ghost** [comment]
It is saying "no availability"

**Comment by rcarle3911** [comment]
Editing a reservation always checks for availability regardless of date changes. And even if the date changes, the reservation in question counts itself as part of the algorithm. I can easily make it not check for availability if no change to the dates or rmtype is detected. However, making it not count itself will be more complicated.

**Comment by rcarle3911** [comment]
I think I can exclude itself from the search with mongodb.
