### ISSUE TITLE
Reservations, Check-in, Check-out

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#142]
- [x] 1 After hiding a column the hide button at the top of the grid doesn't do anything. 
shouldn't it unhide stuff?? 
a refresh of the grid brings them back. 
Is there an option to remove this functionality from the grid?

- [x] 2 Size drop down doesn't do anything.

**Comment by jmoore4** [comment]
supposed to be drop-downs -> http://institut-de-genomique.github.io/Ultimate-DataTable/ 

I will just have to remove them since I can't get them to work. Another issue with it being in the tabs I think. Nothing wants to play nice with me it seems.

**Comment by ghost** [comment]
Yeah Tabs are kinda a $%@#$ in angularjs

**Comment by jmoore4** [comment]
yeah, really

**Comment by jmoore4** [comment]
removed
