### ISSUE TITLE
Manager / Rooms

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#146]
- [x] 1 When changing a room type it doesn't save to the database. 

- [x] 2 Filtering by room type doesn't work

**Comment by ghost** [comment]
task 1: If you change the room number it will change the room type with it. 
same error response as #147 task 1
@rcarle3911 @WilsonC2017

**Comment by jmoore4** [comment]
Maybe this will help?

https://docs.angularjs.org/tutorial/step_05

**Comment by rcarle3911** [comment]
This bug was caused by the _id issue similar to the room types.
