### ISSUE TITLE
Manager / Room Types 

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#147]
- [ ] 1 Modifying room text doesn't work. 

- [x] 2 if you add a ton of text it looks like crap on the table. 

- [x] 3 Deleting a room type doesn't refresh the table

**Comment by ghost** [comment]
Task 1 is returning this on an update. 
{"data":"Room Type with name Room already exists.","status":400,"config":{"method":"PUT","transformRequest":[null],"transformResponse":[null],"url":"/api/protected/room/type/5855df913dfdd72ff5bc44a4","data":{"_id":"5855df913dfdd72ff5bc44a4","name":"Room","desc":"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla tempor vehicula lorem. Sed sagittis lacus urna, at cursus sem laoreet vitae. Duis placerat, nunc vitae finibus hendrerit, mi risus rutrum velit, id mollis eros felis at enim. Quisque rutrum sem eget hendrerit mattis. Phasellus a euismod enim. Donec posuere, enim a tincidunt venenatis, mi massa efficitur ipsum, ut dignissim libero nisl quis augue. Ut gravida elit eget magna semper, at ornare sapien lobortis. Phasellus sit amet sapien auctor, tincidunt purus sit amet, aliquam felis. Proin libero tortor, suscipit ac libero nec, dignissim placerat augue. Duis vel efficitur velit, eu blandit nibh.  Maecenas rutrum egestas nunc, in tempor elit pellentesque a. Aliquam erat volutpat. Nunc iaculis eros ut purus commodo luctus. Praesent id molestie ante. Nullam imperdiet consequat elit, non laoreet nunc faucibus eu. Quisque blandit eleifend est non ornare. Sed ut eros a elit ultricies luctus ac vitae erat.","space":3},"headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ODUyMWJkODMzM2YwNGZhZjY2ZWI1NjciLCJncm91cCI6MiwiaWF0IjoxNDgyMDIzNzU1fQ.mR86r8dE32RiOGRrM8MJbpaxtgaAnlHmyM-S1GMLqq8","Content-Type":"application/json;charset=utf-8"}},"statusText":"Bad Request"}

**Comment by ghost** [comment]
@rcarle3911 @WilsonC2017 check out the API Error above when I do a PUT to the room/type API 
leaving the name the same and changing the number or desc causes this (not changing the name) 
if you change the name it works fine.

**Comment by rcarle3911** [comment]
I've seen this problem else where. Javascript has two equality operators === and == as you may already know. === is a strict equality check while == is a little more lax. For some reason the _id field from the front end loses its strict equality to the _id field stored in the database, but the == operator works.
