### ISSUE TITLE
Emp site link back to main site

### ISSUE THREAD

**Issue by rcarle3911** [rcarle3911/Hotel-Reservation-Project#25]
Add a route on the employee site to link back to the customer site.

**Comment by ghost** [comment]
I was thinking about this last night. We can just add the logo image to the index.html page and link it to the homepage or do you want a textual link?

**Comment by rcarle3911** [comment]
The logo would look nice. Remind those employees who they work for!

**Comment by ghost** [comment]
Added image to the center of the page that links back to /app #39 and #40 pushed it into this repo.
