### ISSUE TITLE
Create History Table

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#41]
Create a history table that will be used to show what the user, employees, and manager have done on the site. 

|Who|What|Why|When|Where|
|---|---|---|---|---|
|User1|Created Reservation|null|dd/mmm/yyyy|/app/resrevation|
|Emp1|Check-In|Checked in User1 to Room 212|dd/mmm/yyyy|/emp/checkin.html|
|Mgr1|Deleted Reservation|User1 Reservation for 10/Jun/2016 was deleted|dd/mmm/yyyy|/emp/mangaer.html|
|Emp1|Note|Noise Complaint by RM 101 on RM 201 blah blah blah|dd/mmm/yyyy|/History.html|

We can discuss this in more detail if necessary. Names don't have to be the 5 W's that's just the first thing that came to mind.

**Comment by rcarle3911** [comment]
I think we can create a collection called log which contains the following
```javascript
{
    user: "" // Could be user._id or user.email both fields will be unique and required for the user database
    date: new Date() // Creates an ISO Date object for with the current timestamp.
    action: "" // This could be the name of the function called.
    args: [{}] // Array of objects passed in to the function if any.
    note: "" // We could use this as an optional field for some database functions.
}
```
We could add something to the log anytime any action is performed. Write a list of what kind of functions you want performed on the server side. I'll start work on basics such as create, edit, delete, and get.

**Comment by ghost** [comment]
So this isn't quite what I had in mind here. I'd like a history table not a audit log file. The history table will hold some audit information but not login or an anonymous actions. Also I'd like this to be displayed to the employees and manager on certain pages and with a collection sitting in a file it will take longer to filter and display vs mongodb

**Comment by rcarle3911** [comment]
What sort of actions do you want recorded? I assume add, edit, and deletions to the databases. I can change the args field to something that tracks changes to maybe to the room capacity, base price, and/or total room count. The user database could track changes to permissions and track numbers in groups. Something like this. Where the deltas accumulate per day or session rather than record everything. We can track ChIn/ChOuts per day.

|Database|User|Action|Date|Delta|
|---|---|---|---|---|
|Room|Carle|Add|15/Dec/2016|10|
|User|Fish|Add|12/Dec/2016|2|
|Res-Future|Steele|Del|28/Nov/2016|-4|
|Res-Present|Smith|ChOut|25/Nov/2016|-2|
|Res-Present|Moore|ChIn|22/Nov/2016|3|

We can put it in a file or the database. The database would be the best option.

**Comment by ghost** [comment]
We are talking about two different things at this point. You are talking about an Audit log... Which we should implement but way way down the line if we have time. 

I am talking about a history table that when you go to the Check-in / Check-out Tabs in the employee interface it will show events based on the customer. 

Also if the manager looks up a customer account it will show the events for the customer. 

If we elect to build a room interface (add, edit) then it would show a history of the room. 

This would track when a customer makes a reservation, Checks in, Checks out, or has a complaint. 

This information would mainly be per stored per user in the databases. My who what where why example above was not specific enough so here is what I am thinking. 


|Date|Action|Note|User|Room|CreatedBy|
|---|---|---|---|---|---|
|mmddyy HH:MM:SS|Reservation|Online Reservation made for two nights (12-2-16 to 12-4-16)|HotelGuestName|Null|OnlineReservation|
|mmddyy HH:MM:SS|Reservation|Phone Reservation made for two nights (12-2-16 to 12-4-16)|HotelGuestName2|Null|EmployeeName|
|mmddyy HH:MM:SS|Checkin|Guest Checkin for two nights (12-2-16 to 12-4-16)|HotelGuestName|204|EmployeeName|
|mmddyy HH:MM:SS|Note|Guest Requested More Towels|HotelGuestName|204|EmployeeName|
|mmddyy HH:MM:SS|Note|Guest Requested Late Checkout|HotelGuestName|204|EmployeeName|
|mmddyy HH:MM:SS|MaintIssue|Report of broken lamp|HotelGuestName|204|EmployeeName|
|mmddyy HH:MM:SS|Checkout|Guest checkout on 12-4-16:1300|HotelGuestName|204|EmployeeName|

This will allow us to pull a history of the guest or a history of the room quickly and easily without having to parse through other audit data.

**Comment by ghost** [comment]
Not enough time to implement in final product.
