### ISSUE TITLE
Make home page responsive

### ISSUE THREAD

**Issue by ghost** [rcarle3911/Hotel-Reservation-Project#59]
When resizing the page it should be responsive. 

Nav menu should collapse. Check in widget should move to the left with the page resize.

**Comment by jmhobbs80** [comment]
Added page responsiveness. Min page width still in play due to nav bar but look it over and feel free to close issue.

**Comment by ghost** [comment]
Page is still not responsive. 

http://www.w3schools.com/html/html_responsive.asp

Go to chrome (or browser of choice) simply resize it... can you see all the content. 
You can use chrome dev tools to view different size browsers. 

ipad view 
![homepage](https://cloud.githubusercontent.com/assets/21179203/20806231/a80d17b0-b7bf-11e6-9274-03e7b56d218a.png)

Then menu should shift or condense to a dropdown 
the Reservation form and search box should move with the page resize.

**Comment by jmhobbs80** [comment]
I have it set to a min width to keep the nav bar from stacking, and the text boxes from jumping out of the page. If you have suggestions on how to make this more fluid I'd be interested to hear them.

**Comment by jmhobbs80** [comment]
Done and done. Added a mobile CSS stylesheet. Checked responsiveness on all possible screen sizes.
