### ISSUE TITLE
Create Reservation Database Functions

### ISSUE THREAD

**Issue by rcarle3911** [rcarle3911/Hotel-Reservation-Project#7]
These functions should be in the reservation.service.js file in the main /services folder
- [x] Counts reservations in a time period by room type
- [x] Get reservations in a time period by room type
- [x] Get all reservations in a time period
- [x] Counts reservations in a time period by room capacity
- [x] Get reservations in a time period by room capacity
- [x] Delete reservation by ID
- [x] Delete all reservations by User Email or ID
- [x] Edit reservation by ID
- [x] Get all reservations
- [x] Get all future reservations
- [x] Get all current reservations (Reservations where guests are checked in but not checked out)
- [x] Get all completed reservations
- [x] Get all reservations starting today

**Comment by dsteele0301** [comment]
@rcarle3911 While I created many of the functions in the checklist, I didn't push all of them to the master branch since I wasn't sure what we would be using them for.

Just one example:
"Counts reservations in a time period by room capacity"
-I assumed that each room type would have a set room capacity, so we should only need to query on room types

**Comment by rcarle3911** [comment]
It's possible to have two room types with the same capacity, while having a customer that doesn't care about the type of room. Querying based on room capacity should return all rooms that would fit the requested space. Querying by room type will only return a certain type of room. 

I think when a reservation is made, it should be attached to a specific room type to prevent overbooking. The query by space should only be for information only, such as a quick availability check.

**Comment by dsteele0301** [comment]
Either way, it will be a quick add. Most of the functions I've written or played with today should be easily manipulated to meet these needs.

Example:
"Counts reservations in a time period by room capacity"
and
"Counts reservations in a time period by room type"
should just require something like
- db.rmTypes.find({name: resrvParam.rmType}).count(...)
OR
-- db.rmTypes.find({space: resrvParam.space}).count(...)

**Comment by dsteele0301** [comment]
I guess I was more curious if you want me to push each of these functions in the checklist to the master branch when some will be very similar

**Comment by rcarle3911** [comment]
Ya, most of the query functions will be a few characters different. The biggest hurdle will be creating an HTTP API that makes sense with those functions and is protected against errors. We could make it very basic on the server side and rely on the client side to process a lot of the information. This would make sense, if we wanted to keep the server processing at a minimum. It would also mean a lot of the functions would go unused, but we would have to write a lot more code to parse through the information.

Also, I noticed you created a rmTypes database and a function to count total rooms. The room.service.js maintains a field "room" in the config.json file with the count information. It looks like this:

```javascript
{
	"apiUrl": "http://localhost:3000/api",
	"secret": "U%P2oW+ 9(cxd631a3oY!-wZ3vD:t^ngB1p$ONB;a1K{{>=fdtju%QQXI+ -~T7U",
	"adminEmails": "motelmartian@gmail.com, rcarle3911@gmail.com, jordanf08@gmail.com, jwmooreiv@gmail.com, dsteele0301@gmail.com, smith.glenisha@me.com, audioinstalr@yahoo.com, blacksmith_22@yahoo.com, fish5802@gmail.com",
	"rooms": {
		"type": {
			"Double Queen Deluxe": "1"
		},
		"space": {
			"4": "1"
		}
	}
}
```

I wanted to keep the dynamic nature of the database by being able to add rooms at a whim, while not having to count total rooms everytime a reservation is made. If this were real life, the total number of rooms wouldn't change very often. I can also make the getTypeList available which returns a list of distinct rmTypes from the database. That could represent the rmTypes database.
