### ISSUE TITLE
Update Account page to include upcoming reservation info

### ISSUE THREAD

**Issue by jmhobbs80** [rcarle3911/Hotel-Reservation-Project#81]

**Comment by rcarle3911** [comment]
The commit https://github.com/rcarle3911/Hotel-Reservation-Project/commit/31b7735c10908a3be84734becf51f89148f8da35 adds functionality to /api/protected/reservation/ GET where it sends an array of upcoming reservations for the logged in user.

**Comment by jmhobbs80** [comment]
OK ill try to get something going on this.

**Comment by jmhobbs80** [comment]
I've added a text area for the content to populate but not sure how to properly route the information to the page. Also not sure I can currently create a new reservation on the back end (looked through the emp site with no luck) so I dont think I could test functionality yet either.

**Comment by dsteele0301** [comment]
Data is now being routed to the front end text area, but it need to be handled and displayed better

**Comment by ghost** [comment]
@jmhobbs80 /emp site is still working on supplying data to the grids and generating modals to insert/update the data then will implement the CRUD operations once that is complete. 
I'm working on the Manager pages and should have the users & rooms tables operational by the end of the weekend. 
@jmoore4 is working on the reservations, check-in, check-out pages.

**Comment by jmhobbs80** [comment]
OK sounds good. Nice work thus far.

**Comment by dsteele0301** [comment]
Did some tweaking tonight. The "Upcoming Reservations" on the user account page now looks much nicer by using a table format similar to what is on the employee pages. There is still work that needs to be done on the Account page "Upcoming Reservations" (buttons not functional and I want to include the Room Type Name), but at least it looks better than the previous wall of JSON-formatted strings.
